name: flutter_mediconnect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image_assets/ayusetu.svg
    - assets/image_assets/doctor.png
    - assets/image_assets/doctor_selected.png
    - assets/image_assets/patient_selected.png
    - assets/image_assets/patient.png

  
