name: flutter_mediconnect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image_assets/ayusetu logo.png"
  adaptive_icon_foreground: "assets/image_assets/play_store_512.png"
  adaptive_icon_background: "#ffffff"
flutter:
  uses-material-design: true
  assets:
    - assets/image_assets/ayusetu.svg
    - assets/image_assets/doctor.svg
    - assets/image_assets/patient.svg
    - assets/image_assets/ayusetu white.svg
    - assets/image_assets/google_icon.svg

  
