name: ayusetu
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.3.0
  image_picker: ^1.1.2
  flutter_quill: ^9.3.6


dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image_assets/ayusetu logo.png"
  adaptive_icon_foreground: "assets/image_assets/play_store_512.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/image_assets/ayusetu.svg
    - assets/image_assets/doctor.svg
    - assets/image_assets/patient.svg
    - assets/image_assets/ayusetu white.svg
    - assets/image_assets/google_icon.svg
    - assets/image_assets/ayusetu_logo.png
    - assets/image_assets/3d_avatar_21.png
    - assets/image_assets/medical_image.png
    - assets/image_assets/ayusetu blue.png
    - assets/image_assets/lung_cancer.svg
    - assets/image_assets/pneumonia.svg
    - assets/image_assets/skin_cancer.svg
    - assets/image_assets/consult.svg
    - assets/image_assets/oral_cancer.svg