// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIApL8N38itCPJS4Pl_LETTgNWCQWST54',
    appId: '1:693830583594:web:71c91bbb17a124b349ca53',
    messagingSenderId: '693830583594',
    projectId: 'ayusetu',
    authDomain: 'ayusetu.firebaseapp.com',
    storageBucket: 'ayusetu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsp1Kef3UIpoNMWhwdVXztuCzaCusdt1Q',
    appId: '1:693830583594:android:10726fde2db54c3849ca53',
    messagingSenderId: '693830583594',
    projectId: 'ayusetu',
    storageBucket: 'ayusetu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUNaOW6dqr81gd3q6lf1X_zSqGJp5qtd8',
    appId: '1:693830583594:ios:7db5989ad22500df49ca53',
    messagingSenderId: '693830583594',
    projectId: 'ayusetu',
    storageBucket: 'ayusetu.firebasestorage.app',
    iosBundleId: 'com.example.flutterMediconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUNaOW6dqr81gd3q6lf1X_zSqGJp5qtd8',
    appId: '1:693830583594:ios:7db5989ad22500df49ca53',
    messagingSenderId: '693830583594',
    projectId: 'ayusetu',
    storageBucket: 'ayusetu.firebasestorage.app',
    iosBundleId: 'com.example.flutterMediconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIApL8N38itCPJS4Pl_LETTgNWCQWST54',
    appId: '1:693830583594:web:b678cbd1225c02fd49ca53',
    messagingSenderId: '693830583594',
    projectId: 'ayusetu',
    authDomain: 'ayusetu.firebaseapp.com',
    storageBucket: 'ayusetu.firebasestorage.app',
  );
}
